baseurl = "https://cintia.me/blog/"
languageCode = "en-us"
title = "Someone else's computer"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"
# Add your tracking code to enable Google Analytics
googleAnalytics = ""
# Posts per page
paginate = 10
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."


[params]
	author = "Cintia"
	description = "Everything is awesome"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/avatar.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	gravatar = "cintiadrio@gmail.com"
	headerText = "CI/CD, Cloud, AWS, DevOps, and other random thoughts"
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = "clouds.jpg"
	copyright = "All content in this blog is released under the [WTFPL](http://www.wtfpl.net/) licence.<br>Opinions here are obviously my own and not necessarily the views of my employer.<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)<br>Comments powered by [staticman](//staticman.net/)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = ""
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "cintiadr/blog"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""
